### ISSUE TITLE
Didn't respect uuid v4

### ISSUE THREAD

**Issue by masseuro** [daniellmb/angular-uuid-service#3]
in xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
y have to be [89ab]

**Comment by daniellmb** [comment]
I guess I misunderstood the spec, I see what you mean, x can be 0123456789abcdef and y needs to be 89ab. I'll refactor the service.

**Comment by daniellmb** [comment]
@masseuro v4 compliance verified, thanks for pointing that out.
https://github.com/daniellmb/angular-uuid-service/blob/master/test/spec/angular-uuid-service.spec.js#L67
